---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-cluster-1
  namespace: mongodb
spec:
  members: 3
  version: 4.2.3-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: demo-cluster-confmap
  credentials: opsmanager-org-access-key


  podSpec:
    # "multiple" persistence allows to mount different directories to different Persistent Volumes
    persistence:
      single:        
          storage: 10Gi
    podTemplate:
      spec:
        # This container will be added to each pod as a sidecar
        containers:
        - name: mongodb-enterprise-database
          resources:
            limits:
              memory: "200M"
            requests:
              memory: "100M"

