apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: demo-mongodb-cluster-1-vpa
  namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: demo-mongodb-cluster-1
  updatePolicy:
    updateMode: "Off"