# server-certificates.yaml
#
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ops-manager-db-0
  namespace: mongodb
spec:
  dnsNames:
  - ops-manager-db-0
  - ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local
  duration: 240h0m0s
  issuerRef:
    name: ca-issuer
  renewBefore: 120h0m0s
  secretName: ops-manager-db-0
  subject:
    organizationalUnits:
    - Your Company
  usages:
  # All Server TLS certs need to be created with “server auth” usage!
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ops-manager-db-1
  namespace: mongodb
spec:
  dnsNames:
  - ops-manager-db-1
  - ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local
  duration: 240h0m0s
  issuerRef:
    name: ca-issuer
  renewBefore: 120h0m0s
  secretName: ops-manager-db-1
  subject:
    organizationalUnits:
      - Your Company
  usages:
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ops-manager-db-2
  namespace: mongodb
spec:
  dnsNames:
  - ops-manager-db-2
  - ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local
  duration: 240h0m0s
  issuerRef:
    name: ca-issuer
  renewBefore: 120h0m0s
  secretName: ops-manager-db-2
  subject:
    organizationalUnits:
    - Your Company
  usages:
  - server auth
  - client auth
