---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 2

  # the version of Ops Manager distro to use
  version: 4.4.1

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: adminopsmanager  
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: opsmanager-packages-volume
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - name: opsmanager-packages-volume
                  mountPath: /mongodb-ops-manager/mongodb-releases/
                  
          # imagePullSecret:
          #   - name: regcred

  
  # the Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: "test@test.com"
    # automation.versions.source: "local"
    # automation.versions.directory: "/mongodb-ops-manager/mongodb-releases/"
    mms.preflight.run: "false"
    mms.ignoreInitialUiSetup: "true"    
    mms.replyToEmailAddr: "test@test.com"
    mms.adminEmailAddr: "test@test.com"
    mms.mail.transport: "smtps"
    mms.mail.hostname: "mail.example.com"
    mms.mail.port: "465"


  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    persistent: true
    podSpec:
      cpu: '0.25'
  externalConnectivity:
    # LoadBalancer|NodePort
    type: LoadBalancer
    # optional, corresponds to nodePort port
    # port: 30100
  backup:
    enabled: false
