---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataBase.name }}-crendential
  {{- if not (eq (.Values.operator.watchNamespace | default "*") "*") }}
  namespace: {{ .Values.operator.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
type: Opaque
data:
    user: {{ .Values.dataBase.opsManager.APIKey | b64enc }}
    publicApiKey: {{ .Values.dataBase.opsManager.APISecret | b64enc }}
