---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cluster-2
data:
  projectName: demo-cluster-2
  baseUrl: http://ae25bfead41f711eab34416328af91c3-454098861.us-east-1.elb.amazonaws.com:8080

  # Optional parameters

  # If orgId is omitted a new organization will be created, with the same name as the Project.
  orgId: 5e318b18d4aa2c00643214b7
