---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-cluster-standalone
  namespace: project1
spec:
  version: 4.2.2-ent
  type: Standalone

  opsManager:
    configMapRef:
      name: demo-cluster-2
  credentials: opsmanager-org-access-key

