---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cluster-1
  # namespace: m
data:
  projectName: demo-cluster-1
  baseUrl: https://a477f4b63df22418b9cd39d3e7d33f5e-1134279687.eu-west-1.elb.amazonaws.com:8443

  # Optional parameters

  # If orgId is omitted a new organization will be created, with the same name as the Project.
  orgId: 5f2d31e2eb94525b99e9d30e

  sslMMSCAConfigMap: ca-om
  sslRequireValidMMSServerCertificates: ‘true’
