---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-cluster-1
  namespace: project1
spec:
  members: 3
  version: 4.2.3-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: demo-cluster-1
  credentials: opsmanager-org-access-key

